* Encoding: UTF-8.


RELIABILITY
  /VARIABLES=Q27.0 Q28 Q29
  /SCALE('ALL VARIABLES') ALL
  /MODEL=ALPHA.

COMPUTE choice_size=MEAN(Q27.0,Q28,Q29).
EXECUTE.

T-TEST GROUPS=condition(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=choice_size hungry
  /CRITERIA=CI(.95).

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN 
  /DEPENDENT choice_size
  /METHOD=ENTER hungry.
